version: '3.7'

services:
  app:
    container_name: ${APP_NAME}
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    image: vessel/app
#    ports:
#     - "${APP_PORT}:80"
    environment:
      CONTAINER_ENV: "${APP_ENV}"
      XDEBUG_HOST: "${XDEBUG_HOST}"
      WWWUSER: "${WWWUSER}"
    restart: always
    volumes:
     - .:/var/www/html
    networks:
      - vesselspiritbible
      - apps-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=app-proxy"

      - "traefik.http.routers.${APP_NAME}.entrypoints=http"
      - "traefik.http.routers.${APP_NAME}.rule=Host(`$APP_URL_TRAEFIK`)"
      - "traefik.http.routers.${APP_NAME}-secure.entrypoints=https"
      - "traefik.http.routers.${APP_NAME}-secure.rule=Host(`$APP_URL_TRAEFIK`)"
      - "traefik.http.routers.${APP_NAME}-secure.tls=true"
      - "traefik.http.routers.${APP_NAME}-secure.tls.certresolver=http"
      - "traefik.http.routers.${APP_NAME}.middlewares=https-redirect@file"
      - "traefik.http.routers.${APP_NAME}.middlewares=default-headers@file"

  mysql:
    container_name: ${APP_NAME}_mysql
    image: mysql:5.7
#    ports:
#     - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
     - vesselspiritbiblemysql:/var/lib/mysql
     # - ./docker/mysql/conf.d:/etc/mysql/conf.d
     # - ./docker/mysql/logs:/var/log/mysql
    networks:
     - vesselspiritbible

  phpmyadmin:
    container_name: ${APP_NAME}_phpmyadmin
    image: phpmyadmin
    restart: always
#    ports:
#      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
      - UPLOAD_LIMIT=300M
    networks:
      - vesselspiritbible
      - apps-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=app-proxy"

      - "traefik.http.routers.${APP_NAME}_pma.entrypoints=http"
      - "traefik.http.routers.${APP_NAME}_pma.rule=Host(`$APP_URL_PMA_TRAEFIK`)"
      - "traefik.http.routers.${APP_NAME}_pma-secure.entrypoints=https"
      - "traefik.http.routers.${APP_NAME}_pma-secure.rule=Host(`$APP_URL_PMA_TRAEFIK`)"
      - "traefik.http.routers.${APP_NAME}_pma-secure.tls=true"
      - "traefik.http.routers.${APP_NAME}_pma-secure.tls.certresolver=http"
      - "traefik.http.routers.${APP_NAME}_pma.middlewares=https-redirect@file"
      - "traefik.http.routers.${APP_NAME}_pma.middlewares=default-headers@file"

networks:
  vesselspiritbible:
    driver: "bridge"
  apps-proxy:
    external: true

volumes:
  vesselspiritbiblemysql:
    driver: "local"
